/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Root */
        get: operations["get_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RagChatRequest */
        RagChatRequest: {
            /**
             * Query
             * @description ユーザーからの問い合わせ内容
             */
            query: string;
            /**
             * Top K
             * @description 取得するドキュメントの上位K件数
             */
            top_k: number | null;
            /**
             * @description サーチモードの指定
             * @default full
             */
            search_mode: components["schemas"]["SearchMode"] | null;
            /**
             * Model
             * @description 使用する言語モデルの指定
             * @default gpt-4o
             */
            model: string;
        };
        /** RagChatResponse */
        RagChatResponse: {
            /**
             * Query
             * @description ユーザーからの問い合わせ内容
             */
            query: string;
            /**
             * Response
             * @description RAGを経由した応答
             */
            response: string;
            /**
             * Documents
             * @description 応答生成に使用されたドキュメントのリスト
             */
            documents: string[];
            /**
             * Search Mode
             * @description サーチモード
             */
            search_mode: string;
        };
        /**
         * SearchMode
         * @enum {string}
         */
        SearchMode: "full" | "hybrid" | "semantic";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
